### ISSUE TITLE
背景透明化＋厳密平均値

### ISSUE THREAD

**Issue by daichisaito525** [kazux2/emojineer#14]

**Comment by kazux2** [comment]
絵文字でカラーパレットを作る #11 の黄色いキャラがキモくなる問題がこのイシューで解決する予定。
仮説：絵文字の平均rgbが白込みの値なので、比較対象の色の濃さを補うために絵文字自体がどす黒いものが選ばれ、黄色はその影響を受けやすいのでは

**Comment by daichisaito525** [comment]
RGB平均値をcv2のresizeではなく厳密にもとめる。（resizeは平均値とはズレている）

**Comment by kazux2** [comment]
#18 #19 で実装完了。
